### ISSUE TITLE
please add opacity slider

### ISSUE THREAD

**Issue by JackDougherty** [OnTheLine/otl-redlining#15]
@ilyankou - please add your amazing opacity slider to the bottom-left corner, above the scale

**Comment by ilyankou** [comment]
Jack,
I added a slider, but also did the following aesthetic changes:

* I changed the borders (width from 2 to 1), and differentiated town boundaries (gray) vs zones (black), to make it look better (in my humble opinion, of course), and because it was very hard to distinguish when both types were black 2px-wide.

* I added this line `map.fitBounds(choroplethLayer.getBounds())` so that as soon as the choropleth is loaded, the map expands if it has space. It won't expand if you put it in a small iframe. Let me know if you want this removed (it just appeared too small on my big screen).

**Comment by JackDougherty** [comment]
Looks fabulous -- thanks!
